// Starter food library.
// Note: This is not “all foods on the internet”. The app supports adding your own foods.

export const BUILTIN_FOODS = [
  // ---------------- Drinks ----------------
  {
    id: "water",
    name: "Water",
    category: "Drink",
    caloriesPerServing: 0,
    servingLabel: "1 glass (250ml)",
    imageQuery: "water glass",
    ingredients: ["Water"],
    tags: ["zero", "hydration"],
  },
  {
    id: "cola",
    name: "Cola",
    category: "Drink",
    caloriesPerServing: 140,
    servingLabel: "1 can (330ml)",
    imageQuery: "cola drink",
    ingredients: ["Carbonated water", "Sugar", "Caramel color"],
    tags: ["soda", "cola"],
  },
  {
    id: "orange-juice",
    name: "Orange juice",
    category: "Drink",
    caloriesPerServing: 110,
    servingLabel: "1 glass (250ml)",
    imageQuery: "orange juice",
    ingredients: ["Orange juice"],
    tags: ["juice"],
  },
  {
    id: "milk-1pct",
    name: "Milk (1%)",
    category: "Drink",
    caloriesPerServing: 105,
    servingLabel: "1 glass (250ml)",
    imageQuery: "milk",
    ingredients: ["Milk"],
    tags: ["dairy"],
  },
  {
    id: "green-tea",
    name: "Green tea (unsweetened)",
    category: "Drink",
    caloriesPerServing: 0,
    servingLabel: "1 cup",
    imageQuery: "green tea cup",
    ingredients: ["Green tea"],
    tags: ["tea", "zero"],
  },
  {
    id: "iced-coffee-sweet",
    name: "Iced coffee (sweetened)",
    category: "Drink",
    caloriesPerServing: 110,
    servingLabel: "1 cup (250ml)",
    imageQuery: "iced coffee",
    ingredients: ["Coffee", "Sugar", "Milk (optional)"],
    tags: ["coffee"],
  },

  // ---------------- Ingredients ----------------
  {
    id: "olive-oil-1tbsp",
    name: "Olive oil",
    category: "Ingredient",
    caloriesPerServing: 119,
    servingLabel: "1 tbsp (15ml)",
    imageQuery: "olive oil bottle",
    ingredients: ["Olive oil"],
    tags: ["fat"],
  },
  {
    id: "butter-1tbsp",
    name: "Butter",
    category: "Ingredient",
    caloriesPerServing: 102,
    servingLabel: "1 tbsp",
    imageQuery: "butter",
    ingredients: ["Butter"],
    tags: ["fat"],
  },
  {
    id: "sugar-1tsp",
    name: "Sugar",
    category: "Ingredient",
    caloriesPerServing: 16,
    servingLabel: "1 tsp",
    imageQuery: "sugar",
    ingredients: ["Sugar"],
    tags: ["sweetener"],
  },
  {
    id: "bread-slice",
    name: "Bread slice",
    category: "Ingredient",
    caloriesPerServing: 80,
    servingLabel: "1 slice",
    imageQuery: "bread",
    ingredients: ["Flour", "Water", "Yeast", "Salt"],
    tags: ["carbs"],
  },

  // ---------------- Snacks ----------------
  {
    id: "banana",
    name: "Banana",
    category: "Snack",
    caloriesPerServing: 105,
    servingLabel: "1 medium",
    imageQuery: "banana",
    ingredients: ["Banana"],
    tags: ["fruit"],
  },
  {
    id: "apple",
    name: "Apple",
    category: "Snack",
    caloriesPerServing: 95,
    servingLabel: "1 medium",
    imageQuery: "apple",
    ingredients: ["Apple"],
    tags: ["fruit"],
  },
  {
    id: "yogurt-greek",
    name: "Greek yogurt (plain)",
    category: "Snack",
    caloriesPerServing: 100,
    servingLabel: "170g",
    imageQuery: "greek yogurt",
    ingredients: ["Milk", "Live cultures"],
    tags: ["dairy", "protein"],
  },
  {
    id: "protein-bar",
    name: "Protein bar",
    category: "Snack",
    caloriesPerServing: 200,
    servingLabel: "1 bar",
    imageQuery: "protein bar",
    ingredients: ["Protein blend", "Sweeteners", "Cocoa (optional)"],
    tags: ["protein"],
  },
  {
    id: "dark-chocolate-1oz",
    name: "Dark chocolate",
    category: "Snack",
    caloriesPerServing: 170,
    servingLabel: "1 oz (28g)",
    imageQuery: "dark chocolate",
    ingredients: ["Cocoa solids", "Sugar", "Cocoa butter"],
    tags: ["sweet"],
  },
  {
    id: "mixed-nuts-1oz",
    name: "Mixed nuts",
    category: "Snack",
    caloriesPerServing: 170,
    servingLabel: "1 oz (28g)",
    imageQuery: "mixed nuts",
    ingredients: ["Nuts"],
    tags: ["snack", "fat"],
  },
  {
    id: "peanut-butter-2tbsp",
    name: "Peanut butter",
    category: "Snack",
    caloriesPerServing: 190,
    servingLabel: "2 tbsp",
    imageQuery: "peanut butter",
    ingredients: ["Peanuts"],
    tags: ["fat", "protein"],
  },
  {
    id: "hummus-2tbsp",
    name: "Hummus",
    category: "Snack",
    caloriesPerServing: 70,
    servingLabel: "2 tbsp",
    imageQuery: "hummus",
    ingredients: ["Chickpeas", "Tahin", "Olive oil", "Lemon juice"],
    tags: ["dip"],
  },
  {
    id: "popcorn-air",
    name: "Air-popped popcorn",
    category: "Snack",
    caloriesPerServing: 90,
    servingLabel: "3 cups",
    imageQuery: "popcorn",
    ingredients: ["Corn kernels"],
    tags: ["fiber"],
  },
  {
    id: "cheddar-oz",
    name: "Cheddar cheese",
    category: "Snack",
    caloriesPerServing: 113,
    servingLabel: "1 oz (28g)",
    imageQuery: "cheddar cheese",
    ingredients: ["Milk", "Cheese cultures", "Salt"],
    tags: ["dairy"],
  },
  {
    id: "bagel",
    name: "Bagel",
    category: "Snack",
    caloriesPerServing: 270,
    servingLabel: "1 small bagel",
    imageQuery: "bagel",
    ingredients: ["Flour", "Water", "Yeast", "Salt"],
    tags: ["bread"],
  },
  {
    id: "granola-1cup",
    name: "Granola",
    category: "Snack",
    caloriesPerServing: 480,
    servingLabel: "1 cup",
    imageQuery: "granola",
    ingredients: ["Oats", "Honey", "Nuts", "Dried fruit (optional)"],
    tags: ["breakfast", "snack"],
  },
  {
    id: "candy",
    name: "Candy (generic)",
    category: "Snack",
    caloriesPerServing: 150,
    servingLabel: "1 small serving",
    imageQuery: "candy",
    ingredients: ["Sugar", "Flavorings"],
    tags: ["sweet"],
  },

  // ---------------- Meals ----------------
  {
    id: "chicken-breast-100g",
    name: "Chicken breast (cooked)",
    category: "Meal",
    caloriesPerServing: 165,
    servingLabel: "100g cooked",
    imageQuery: "grilled chicken",
    ingredients: ["Chicken breast"],
    tags: ["protein", "lean"],
  },
  {
    id: "salmon-100g",
    name: "Salmon (cooked)",
    category: "Meal",
    caloriesPerServing: 208,
    servingLabel: "100g cooked",
    imageQuery: "salmon dinner",
    ingredients: ["Salmon"],
    tags: ["protein", "omega-3"],
  },
  {
    id: "beef-lean-100g",
    name: "Lean beef (cooked)",
    category: "Meal",
    caloriesPerServing: 250,
    servingLabel: "100g cooked",
    imageQuery: "steak",
    ingredients: ["Beef"],
    tags: ["protein"],
  },
  {
    id: "rice-cooked-1cup",
    name: "Rice (cooked)",
    category: "Meal",
    caloriesPerServing: 205,
    servingLabel: "1 cup cooked (158g)",
    imageQuery: "rice bowl",
    ingredients: ["Rice"],
    tags: ["carbs"],
  },
  {
    id: "pasta-cooked-1cup",
    name: "Pasta (cooked)",
    category: "Meal",
    caloriesPerServing: 220,
    servingLabel: "1 cup cooked",
    imageQuery: "pasta plate",
    ingredients: ["Pasta"],
    tags: ["carbs"],
  },
  {
    id: "oatmeal-1cup",
    name: "Oatmeal (cooked)",
    category: "Meal",
    caloriesPerServing: 170,
    servingLabel: "1 cup cooked",
    imageQuery: "oatmeal",
    ingredients: ["Oats", "Water (or milk)"],
    tags: ["breakfast", "fiber"],
  },
  {
    id: "eggs-2",
    name: "Eggs",
    category: "Meal",
    caloriesPerServing: 144,
    servingLabel: "2 large eggs",
    imageQuery: "eggs",
    ingredients: ["Eggs"],
    tags: ["protein"],
  },
  {
    id: "tuna-150g",
    name: "Tuna (drained)",
    category: "Meal",
    caloriesPerServing: 160,
    servingLabel: "1 can (150g drained)",
    imageQuery: "tuna",
    ingredients: ["Tuna"],
    tags: ["protein"],
  },
  {
    id: "tofu-150g",
    name: "Tofu",
    category: "Meal",
    caloriesPerServing: 180,
    servingLabel: "150g",
    imageQuery: "tofu",
    ingredients: ["Soybeans", "Coagulant"],
    tags: ["plant", "protein"],
  },
];

export function normalizeFoodForStorage(food) {
  function deriveBaseFromServingLabel(label) {
    const s = String(label || "");
    // Tries to extract the first "number g" from the serving label, e.g. "100g cooked" or "1 oz (28g)".
    const m = s.match(/(\d+(?:\.\d+)?)\s*g\b/i);
    if (!m) return null;
    const n = Number(m[1]);
    return Number.isFinite(n) && n > 0 ? n : null;
  }

  const explicitBaseAmount = Number(food.caloriesBaseAmount);
  const baseAmountFromLabel = deriveBaseFromServingLabel(food.servingLabel);

  const baseAmount =
    Number.isFinite(explicitBaseAmount) && explicitBaseAmount > 0
      ? explicitBaseAmount
      : baseAmountFromLabel !== null
        ? baseAmountFromLabel
        : 1;

  const baseUnit =
    baseAmountFromLabel !== null || (Number.isFinite(explicitBaseAmount) && explicitBaseAmount > 0) ? "g" : "serving";

  // Ensures we store a predictable shape from user input.
  return {
    id: String(food.id || "").trim(),
    name: String(food.name || "").trim(),
    category: String(food.category || "Snack"),
    caloriesPerServing: Number(food.caloriesPerServing || 0),
    servingLabel: String(food.servingLabel || "").trim(),
    imageQuery: String(food.imageQuery || "").trim(),
    imageUrl: String(food.imageUrl || "").trim(),
    caloriesBaseAmount: baseAmount,
    caloriesBaseUnit: baseUnit,
    ingredients: Array.isArray(food.ingredients) ? food.ingredients : [],
    tags: Array.isArray(food.tags) ? food.tags : [],
  };
}

