/**
 * Genereert data/nl-supermarkt-staples.json — indicatieve kcal (ongeveer NEVO/ETI-achtig).
 * Run: node scripts/gen_nl_supermarkt_staples.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const out = path.join(root, "data", "nl-supermarkt-staples.json");

const T = ["nederland", "supermarkt", "albert heijn", "jumbo", "lidl"];

function row(id, name, category, kcal, servingLabel, imageQuery, tags = []) {
  return {
    id: `staple:${id}`,
    name,
    category,
    caloriesPerServing: kcal,
    servingLabel,
    imageQuery,
    ingredients: [name.replace(/\s*\(.*$/, "").trim()],
    tags: [...new Set([...tags, ...T])],
  };
}

const items = [
  row("melk-vol", "Volle melk", "Drink", 66, "100 ml", "melk pak vol", ["melk", "zuivel"]),
  row("melk-halfvol", "Halfvolle melk", "Drink", 46, "100 ml", "halfvolle melk", ["melk"]),
  row("melk-mager", "Magere melk", "Drink", 35, "100 ml", "magere melk", ["melk"]),
  row("karnemelk", "Karnemelk", "Drink", 80, "250 ml", "karnemelk", ["zuivel"]),
  row("chocomel", "Chocomel (pak)", "Drink", 84, "100 ml", "chocomel", ["chocolademelk"]),
  row("fristi", "Fristi", "Drink", 50, "100 ml", "fristi", ["drinkyoghurt"]),
  row("vla-vanille", "Vla vanille", "Drink", 96, "100 ml", "vanille vla", ["vla", "toetje"]),
  row("kwark-magere", "Magere kwark naturel", "Snack", 70, "100 g", "magere kwark", ["kwark", "eiwit"]),
  row("kwark-vol", "Volle kwark naturel", "Snack", 103, "100 g", "volle kwark", ["kwark"]),
  row("griekse-yoghurt", "Griekse yoghurt naturel", "Snack", 120, "100 g", "greek yogurt", ["yoghurt"]),
  row("skyr", "Skyr naturel", "Snack", 66, "100 g", "skyr", ["yoghurt", "ijsland"]),
  row("drinkyoghurt-aardbei", "Drinkyoghurt aardbei", "Drink", 64, "100 ml", "drinkyoghurt", ["yoghurt"]),
  row("appelsap", "Appelsap", "Drink", 45, "100 ml", "appelsap pak", ["sap"]),
  row("sinasappelsap", "Sinaasappelsap", "Drink", 42, "100 ml", "sinaasappelsap", ["sap", "vitamine c"]),
  row("multivitamine-sap", "Multivitaminesap", "Drink", 45, "100 ml", "multivitamine sap", ["sap"]),
  row("spa-rood", "Spa rood / bronwater met bubbels", "Drink", 0, "250 ml", "spa rood", ["water", "bruisend"]),
  row("thee-ijzer", "Kop zwarte thee (met suiker)", "Drink", 30, "250 ml", "thee kop", ["thee"]),
  row("koffie-melk-suiker", "Koffie met melk en suiker", "Drink", 45, "250 ml", "koffie melk", ["koffie"]),
  row("aa-drink", "AA Drink (isotone drank)", "Drink", 24, "100 ml", "aa drink", ["sportdrank"]),
  row("energiedrank", "Energiedrank (blik)", "Drink", 45, "100 ml", "energy drink blik", ["energie"]),
  row("icetea", "Ice tea peach", "Drink", 22, "100 ml", "ice tea", ["thee"]),
  row("brood-wit-snee", "Witbrood (snee)", "Snack", 80, "1 snee (~35 g)", "wit brood snee", ["brood"]),
  row("brood-volkoren-snee", "Volkorenbrood (snee)", "Snack", 75, "1 snee (~35 g)", "volkoren brood", ["brood", "vezel"]),
  row("brood-casino-wit", "Casinobrood wit (snee)", "Snack", 85, "1 snee", "casino brood", ["brood"]),
  row("ontbijtkoek", "Ontbijtkoek (plak)", "Snack", 90, "1 plak (~30 g)", "ontbijtkoek", ["koek", "kruid"]),
  row("beschuit", "Beschuit", "Snack", 35, "1 stuk", "beschuit", ["brood"]),
  row("crackers-haver", "Havercrackers", "Snack", 25, "1 cracker", "haver crackers", ["cracker"]),
  row("tuc-crackers", "Zoute crackers (TUC-achtig)", "Snack", 24, "1 cracker", "tuc crackers", ["cracker", "zout"]),
  row("rijstwafel", "Rijstwafel naturel", "Snack", 35, "1 stuk", "rijstwafel", ["glutenvrij"]),
  row("stroopwafel", "Stroopwafel", "Snack", 140, "1 stuk", "stroopwafel", ["koek", "karamel"]),
  row("speculaas", "Speculaas (2 koeken)", "Snack", 120, "2 stuks", "speculaas", ["pepernoten", "sinterklaas"]),
  row("hagelslag", "Chocolade hagelslag", "Snack", 80, "2 el (~15 g)", "hagelslag", ["chocolade", "broodbeleg"]),
  row("pindakaas", "Pindakaas", "Snack", 90, "1 el (~15 g)", "pindakaas", ["noten", "broodbeleg"]),
  row("jam-aardbei", "Aardbeienjam", "Snack", 40, "1 el (~15 g)", "aardbeienjam", ["jam"]),
  row("appelstroop", "Appelstroop", "Snack", 45, "1 el (~15 g)", "appelstroop", ["stroop"]),
  row("margarine", "Margarine (voor op brood)", "Ingredient", 36, "10 g", "margarine kuip", ["vet"]),
  row("roomboter", "Roomboter", "Ingredient", 75, "10 g", "roomboter", ["boter"]),
  row("kaas-belegen-plak", "Belegen kaas (plak)", "Snack", 120, "30 g (1 plak)", "kaas plak", ["kaas", "zuivel"]),
  row("kaas-jong-geraspt", "Jonge kaas geraspt", "Ingredient", 400, "100 g", "geraspte kaas", ["kaas"]),
  row("mozzarella", "Mozzarella (bol)", "Ingredient", 250, "125 g", "mozzarella bol", ["kaas", "italiaans"]),
  row("feta", "Feta", "Ingredient", 80, "30 g", "feta kaas", ["kaas", "salade"]),
  row("ham-gekookt", "Gekookte ham (plakken)", "Meal", 30, "2 plakjes (~40 g)", "ham plakjes", ["vlees", "varken"]),
  row("kipfilet-plak", "Kipfilet (plakken)", "Meal", 50, "2 plakjes (~50 g)", "kipfilet", ["kip"]),
  row("rookworst", "Rookworst (AH/Jumbo)", "Meal", 320, "1 stuk (~150 g)", "rookworst", ["worst", "bbq"]),
  row("leverworst", "Leverworst (plak)", "Snack", 80, "1 dikke plak", "leverworst", ["worst"]),
  row("filet-americain", "Filet américain", "Snack", 250, "100 g", "filet americain", ["rund", "broodbeleg"]),
  row("salami-plak", "Salami (plakken)", "Snack", 90, "3 plakjes", "salami", ["vlees"]),
  row("kipgehakt-rauw", "Kipgehakt (rauw, bakken)", "Ingredient", 150, "100 g", "kip gehakt", ["kip", "gehakt"]),
  row("rund-gehakt", "Rundergehakt (half-om-half)", "Ingredient", 250, "100 g", "gehakt half om half", ["rund", "varken"]),
  row("spekblokjes", "Spekblokjes (bakken)", "Ingredient", 400, "100 g", "spekblokjes", ["varken", "bakvet"]),
  row("kipdijfilet", "Kipdijfilet (gegrild)", "Meal", 280, "150 g", "kipdij", ["kip"]),
  row("zalm-gerookt", "Gerookte zalm", "Meal", 200, "100 g", "gerookte zalm", ["vis", "omega"]),
  row("tonijn-water", "Tonijn in water (uitgelekt)", "Meal", 116, "1 klein blikje (~80 g vis)", "tonijn blik", ["vis"]),
  row("makreel-tomaten", "Makreel in tomatensaus", "Meal", 220, "1 blik (~170 g)", "makreel blik", ["vis"]),
  row("haring", "Hollandse nieuwe haring", "Meal", 180, "1 stuk", "haring vis", ["vis"]),
  row("ei-gekookt", "Ei gekookt", "Meal", 78, "1 middelgroot ei", "gekookt ei", ["eiwit"]),
  row("tofu-vast", "Tofu naturel (vast)", "Ingredient", 120, "150 g", "tofu blok", ["plantaardig", "eiwit"]),
  row("tempeh", "Tempeh", "Ingredient", 190, "100 g", "tempeh", ["soja"]),
  row("falafel", "Falafelballetjes (diepvries/vers)", "Meal", 200, "4 stuks (~80 g)", "falafel", ["vegetarisch"]),
  row("hummus", "Hummus", "Snack", 180, "100 g", "hummus", ["kikkererwt", "dip"]),
  row("mayonaise", "Mayonaise", "Ingredient", 100, "1 el (~15 g)", "mayonaise pot", ["saus"]),
  row("ketchup", "Ketchup", "Ingredient", 15, "1 el (~15 g)", "ketchup fles", ["saus"]),
  row("joppiesaus", "Joppiesaus", "Ingredient", 100, "30 g", "joppiesaus", ["friet", "saus"]),
  row("curry-ketchup", "Curry ketchup", "Ingredient", 20, "1 el", "curry ketchup", ["saus"]),
  row("mosterd", "Mosterd", "Ingredient", 15, "1 el", "mosterd pot", ["saus"]),
  row("olijfolie", "Olijfolie (extra vierge)", "Ingredient", 90, "1 el (~10 g)", "olijfolie", ["olie"]),
  row("zonnebloemolie", "Zonnebloemolie", "Ingredient", 90, "1 el (~10 g)", "zonnebloemolie", ["olie"]),
  row("aardappel-koken", "Aardappel gekookt", "Ingredient", 87, "100 g", "gekookte aardappel", ["aardappel"]),
  row("friet-portie", "Friet / patat (cafetaria)", "Meal", 450, "150 g portie", "patat friet", ["aardappel"]),
  row("kroket", "Kroket", "Snack", 250, "1 stuk", "kroket", ["snack", "frituur"]),
  row("frikandel", "Frikandel", "Snack", 180, "1 stuk", "frikandel", ["snack"]),
  row("bitterbal", "Bitterbal", "Snack", 60, "1 stuk", "bitterbal", ["borrel"]),
  row("bapao-kip", "Bapao kip", "Meal", 280, "1 broodje", "bapao", ["broodje"]),
  row("tosti-ham-kaas", "Tosti ham-kaas", "Meal", 350, "1 tosti", "tosti", ["brood", "kaas"]),
  row("diepvries-pizza", "Diepvries pizza (magnetron)", "Meal", 240, "1/4 pizza (~125 g)", "diepvries pizza", ["pizza"]),
  row("lasagne-kant", "Lasagne uit de oven (kant-en-klaar)", "Meal", 560, "400 g portie", "lasagne", ["pasta"]),
  row("nasi-kant", "Nasi goreng (kant-en-klaar)", "Meal", 500, "300 g", "nasi goreng", ["rijst"]),
  row("roti", "Surinaamse roti rol", "Meal", 450, "1 rol", "roti rol", ["kip", "kruid"]),
  row("erwtensoep", "Erwtensoep (snert)", "Meal", 180, "300 ml kom", "erwtensoep", ["soep", "winter"]),
  row("stamppot-boerenkool", "Boerenkoolstamppot met rookworst", "Meal", 650, "1 bord (~500 g)", "boerenkool stamppot", ["stamppot"]),
  row("hutspot", "Hutspot met klapstuk", "Meal", 580, "1 bord", "hutspot", ["stamppot"]),
  row("spaghetti-80-droog", "Spaghetti (droog, gekookt portie)", "Ingredient", 280, "80 g droog → ~220 g gekookt", "spaghetti", ["pasta"]),
  row("penne-droog", "Penne (droog, gekookt portie)", "Ingredient", 270, "80 g droog", "penne pasta", ["pasta"]),
  row("rijst-basmati-droog", "Basmatirijst (droog, gekookt portie)", "Ingredient", 210, "60 g droog", "basmati rijst", ["rijst"]),
  row("couscous-droog", "Couscous (droog, bereid)", "Ingredient", 200, "60 g droog", "couscous", ["pasta"]),
  row("havermout", "Havermout", "Snack", 150, "40 g droog + water", "havermout", ["ontbijt"]),
  row("cornflakes", "Cornflakes", "Snack", 115, "30 g + melk apart", "cornflakes", ["ontbijt"]),
  row("muesli-noten", "Muesli met noten", "Snack", 190, "45 g", "muesli", ["ontbijt"]),
  row("bruine-bonen", "Bruine bonen (pot, uitgelekt)", "Ingredient", 100, "100 g", "bruine bonen pot", ["bonen"]),
  row("kidneybonen", "Kidneybonen (blik)", "Ingredient", 100, "100 g", "kidney bonen", ["bonen"]),
  row("kikkererwten", "Kikkererwten (blik, uitgelekt)", "Ingredient", 120, "100 g", "kikkererwten", ["bonen"]),
  row("mais", "Mais (blik, uitgelekt)", "Ingredient", 90, "100 g", "mais blik", ["groente"]),
  row("tomaat", "Tomaat", "Ingredient", 18, "100 g", "tomaat", ["groente"]),
  row("komkommer", "Komkommer", "Ingredient", 15, "100 g", "komkommer", ["groente"]),
  row("paprika", "Paprika rood", "Ingredient", 31, "100 g", "paprika", ["groente"]),
  row("ui", "Ui", "Ingredient", 40, "100 g", "ui groente", ["groente"]),
  row("broccoli", "Broccoli (gestoomd)", "Ingredient", 35, "100 g", "broccoli", ["groente"]),
  row("spinazie-diepvries", "Spinazie (diepvries, bereid)", "Ingredient", 30, "100 g", "spinazie", ["groente"]),
  row("avocado", "Avocado", "Ingredient", 160, "half avocado (~100 g)", "avocado", ["vet", "gezond"]),
  row("banaan", "Banaan", "Snack", 105, "1 middel (120 g)", "banaan", ["fruit"]),
  row("appel", "Appel", "Snack", 70, "1 middel (130 g)", "appel fruit", ["fruit"]),
  row("sinaasappel", "Sinaasappel", "Snack", 62, "1 middel (150 g)", "sinaasappel", ["fruit"]),
  row("drop-zacht", "Drop (zoet)", "Snack", 300, "100 g", "drop snoep", ["snoep"]),
  row("pepernoten", "Pepernoten / kruidnoten", "Snack", 430, "100 g", "kruidnoten", ["sinterklaas"]),
  row("melkchocolade-reep", "Melkchocolade reep", "Snack", 125, "1 reep (25 g)", "melkchocolade reep", ["chocolade"]),
  row("pure-chocolade", "Pure chocolade 70%", "Snack", 170, "30 g", "pure chocolade", ["chocolade"]),
  row("winegums", "Winegums", "Snack", 320, "100 g", "winegums", ["snoep"]),
  row("chips-naturel", "Chips naturel", "Snack", 536, "100 g", "chips zak", ["aardappel", "zout"]),
  row("olijven-groen", "Groene olijven", "Snack", 140, "50 g", "olijven groen", ["italiaans"]),
  row("augurk", "Augurken", "Snack", 5, "1 augurk", "augurk pot", ["zuur"]),
  row("croissant", "Croissant", "Snack", 230, "1 stuk", "croissant", ["ontbijt", "bakker"]),
  row("donut", "Donut geglazuurd", "Snack", 280, "1 stuk", "donut", ["gebak"]),
  row("muffin", "Muffin chocolade", "Snack", 400, "1 grote muffin", "muffin", ["gebak"]),
  row("yoghurt-drink-mango", "Yoghurtdrink mango", "Drink", 60, "100 ml", "yoghurt drink", ["yoghurt"]),
  row("icelatte", "IJs latte (kant-en-klaar)", "Drink", 50, "100 ml", "ice latte", ["koffie"]),
  row("kokosmelk-blik", "Kokosmelk (light, koken)", "Ingredient", 50, "100 ml", "kokosmelk blik", ["kokos", "curry"]),
  row("bouillonblokje", "Bouillonblokje (bereid in water)", "Drink", 10, "250 ml kop", "bouillon", ["soep"]),
  row("sojasaus", "Sojasaus", "Ingredient", 53, "100 ml", "sojasaus fles", ["aziatisch"]),
  row("sambal", "Sambal oelek", "Ingredient", 20, "1 tl (~5 g)", "sambal", ["pittig"]),
  row("pesto-groen", "Pesto alla genovese", "Ingredient", 350, "100 g", "pesto groen", ["pasta", "saus"]),
  row("passata", "Passata / gezeefde tomaten", "Ingredient", 24, "100 g", "passata", ["tomaat", "italiaans"]),
  row("zure-kool", "Zuurkool (pot)", "Ingredient", 20, "100 g", "zuurkool", ["groente"]),
  row("spruitjes", "Spruitjes (gekookt)", "Ingredient", 43, "100 g", "spruitjes", ["groente"]),
  row("wortelen", "Wortelen (gekookt)", "Ingredient", 35, "100 g", "wortelen", ["groente"]),
  row("bloemkool", "Bloemkool (gekookt)", "Ingredient", 25, "100 g", "bloemkool", ["groente"]),
  row("courgette", "Courgette", "Ingredient", 17, "100 g", "courgette", ["groente"]),
  row("aubergine", "Aubergine", "Ingredient", 25, "100 g", "aubergine", ["groente"]),
  row("perzik-op-siroop", "Perziken op lichte siroop", "Snack", 60, "100 g uitgelekt", "perzik blik", ["fruit"]),
  row("pruimen", "Ontpitte pruimen (droog)", "Snack", 240, "100 g", "pruimen gedroogd", ["fruit", "vezel"]),
  row("rozijnen", "Rozijnen", "Snack", 300, "100 g", "rozijnen", ["fruit"]),
  row("pinda-gezouten", "Pinda's gezouten", "Snack", 600, "100 g", "pinda's", ["noten"]),
  row("amandelen", "Amandelen", "Snack", 600, "100 g", "amandelen", ["noten"]),
  row("walnoten", "Walnoten", "Snack", 650, "100 g", "walnoten", ["noten"]),
  row("zoute-sticks", "Zoute sticks / breadsticks", "Snack", 400, "100 g", "zoute sticks", ["borrel"]),
  row("kaasstengels", "Kaasstengels (diepvries)", "Snack", 320, "100 g (4–5 stuks)", "kaasstengels", ["borrel"]),
  row("oliebollen", "Oliebol (met poedersuiker)", "Snack", 280, "1 stuk", "oliebol", ["nieuwjaar"]),
  row("appelflap", "Appelflap (bakker)", "Snack", 200, "1 stuk", "appelflap", ["gebak"]),
  row("worstenbroodje", "Worstenbroodje", "Snack", 320, "1 stuk", "worstenbroodje", ["vlees"]),
  row("kaasbroodje", "Kaasbroodje (bakker)", "Snack", 380, "1 stuk", "kaasbroodje", ["kaas"]),
  row("yoghurt-hoepelm", "Yoghurt met hoestreep (perzik)", "Drink", 85, "125 ml", "yoghurt drink perzik", ["yoghurt"]),
  row("limonadesiroop", "Limonadesiroop (aangelengd)", "Drink", 40, "250 ml glas", "limonade siroop", ["fris"]),
  row("radler-00", "Radler 0.0", "Drink", 27, "100 ml", "radler 0.0", ["bier", "alcoholvrij"]),
  row("appelmoes", "Appelmoes zonder toegevoegde suiker", "Snack", 50, "100 g", "appelmoes", ["fruit", "kind"]),
  row("custard", "Vanillevla / custard (beker)", "Drink", 95, "125 ml", "vanille vla beker", ["vla"]),
  row("roomijs-bek", "Roomijs vanille (schep)", "Snack", 135, "100 ml (~2 bolletjes)", "vanille ijs", ["ijs"]),
  row("magnum-achtig", "IJslolly melkchocolade (Magnum-achtig)", "Snack", 290, "1 stuk", "magnum ijs", ["ijs"]),
  row("slagroom-spuitbus", "Slagroom (spuitbus)", "Ingredient", 45, "2 el (~15 g)", "slagroom spuitbus", ["room"]),
  row("cottage-cheese", "Cottage cheese", "Snack", 98, "100 g", "cottage cheese", ["kaas", "eiwit"]),
  row("roomkaas-natuur", "Roomkaas naturel (Philadelphia-achtig)", "Ingredient", 250, "100 g", "roomkaas", ["kaas", "dip"]),
  row("zure-room", "Zure room / crème fraîche", "Ingredient", 200, "100 g", "creme fraiche", ["room"]),
  row("slasaus", "Slasaus (yoghurt)", "Ingredient", 120, "100 g", "slasaus", ["salade"]),
  row("knackebrod", "Knäckebröd", "Snack", 35, "1 plak", "knackebrod", ["cracker", "vezel"]),
  row("ontbijtgranen-honey", "Ontbijtgranen honing (Corn Flakes-achtig)", "Snack", 380, "100 g", "honey loops", ["ontbijt"]),
  row("granola-honing", "Granola met honing", "Snack", 450, "100 g", "granola", ["ontbijt"]),
  row("pannenkoek", "Pannenkoek (plat)", "Meal", 180, "1 middelgrote", "pannenkoek", ["nederlands"]),
  row("poffertjes", "Poffertjes (met boter en poedersuiker)", "Meal", 350, "10 stuks", "poffertjes", ["nederlands"]),
  row("nasi-kruiden", "Nasi / bami kruidenmix (bereid)", "Ingredient", 180, "100 g bereide rijst", "nasi kruiden", ["kruiden"]),
  row("satésaus", "Pindasaus / satésaus (kant-en-klaar)", "Ingredient", 220, "100 g", "pindasaus", ["indisch"]),
  row("ketjap-manis", "Ketjap manis", "Ingredient", 200, "100 ml", "ketjap manis", ["indisch"]),
  row("rijstnoedels", "Rijstnoedels (droog)", "Ingredient", 360, "100 g droog", "rijstnoedels", ["aziatisch"]),
  row("wokgroente-diepvries", "Wokgroente diepvries", "Ingredient", 45, "100 g", "wok groente", ["groente"]),
  row("kipfiletblokjes", "Kipfiletblokjes (roerbak)", "Meal", 165, "150 g", "kipfilet blokjes", ["kip"]),
  row("biefstuk", "Biefstuk (gegrild)", "Meal", 180, "100 g", "biefstuk", ["rund"]),
  row("speklap", "Speklap (gebakken)", "Meal", 350, "100 g", "speklap", ["varken"]),
  row("schnitzel", "Kipschnitzel (bereid)", "Meal", 220, "1 stuk (~120 g)", "kipschnitzel", ["kip"]),
  row("kipcorn", "Kipcorn", "Snack", 200, "1 stuk", "kipcorn", ["frituur"]),
  row("kipnuggets", "Kipnuggets (oven)", "Snack", 260, "6 stuks (~100 g)", "kip nuggets", ["kip"]),
  row("vegaburger", "Vegaburger (bereid)", "Meal", 180, "1 burger", "vega burger", ["vegetarisch"]),
  row("beyond-style", "Plantaardige burger (Beyond-achtig)", "Meal", 250, "1 burger", "plant based burger", ["vegan"]),
  row("quorn-stukjes", "Quorn stukjes (bereid)", "Meal", 120, "100 g", "quorn", ["vegetarisch"]),
  row("linzensoep", "Linzensoep", "Meal", 90, "250 ml", "linzensoep", ["soep", "vezel"]),
  row("tomatensoep", "Tomatensoep (pak)", "Meal", 45, "250 ml", "tomatensoep", ["soep"]),
  row("groentesoep", "Groentesoep (pak)", "Meal", 35, "250 ml", "groentesoep", ["soep"]),
  row("bouillon-kip", "Kippenbouillon (drink)", "Drink", 15, "250 ml", "kippenbouillon", ["soep"]),
  row("stokbrood", "Stokbrood wit (stuk)", "Snack", 240, "100 g", "stokbrood", ["brood"]),
  row("pistolet", "Pistolet wit", "Snack", 220, "1 bol", "pistolet brood", ["brood"]),
  row("tortilla-wrap", "Tortilla wrap groot", "Ingredient", 180, "1 stuk (~65 g)", "tortilla wrap", ["wrap"]),
  row("nacho-chips", "Nacho tortilla chips", "Snack", 500, "100 g", "nacho chips", ["mexicaans"]),
  row("guacamole-pot", "Guacamole (kant-en-klaar)", "Snack", 160, "100 g", "guacamole", ["avocado"]),
  row("tzatziki", "Tzatziki (kuip)", "Snack", 130, "100 g", "tzatziki", ["yoghurt", "dip"]),
  row("coleslaw", "Coleslaw salade", "Snack", 150, "100 g", "coleslaw", ["salade"]),
  row("rugbrood", "Roggebrood (plak)", "Snack", 90, "1 plak", "roggebrood", ["brood", "vezel"]),
  row("cruesli", "Cruesli chocolade", "Snack", 420, "100 g", "cruesli", ["ontbijt"]),
  row("ontbijtrepen", "Ontbijtrepen muesli", "Snack", 180, "1 reep (35 g)", "ontbijt reep", ["reep"]),
  row("studentenhaver", "Studentenhaver", "Snack", 480, "100 g", "studentenhaver", ["noten", "rozijn"]),
  row("paddestoelen", "Champignons (bak)", "Ingredient", 22, "100 g", "champignons", ["groente"]),
  row("erwten-diepvries", "Doperwten (diepvries)", "Ingredient", 85, "100 g", "doperwten", ["groente"]),
  row("sperziebonen", "Sperziebonen (gekookt)", "Ingredient", 35, "100 g", "sperziebonen", ["groente"]),
  row("rode-kool", "Rode kool (pot)", "Ingredient", 45, "100 g", "rode kool", ["groente"]),
  row("andijvie", "Andijvie (stamppot)", "Ingredient", 20, "100 g", "andijvie", ["groente"]),
  row("endive", "Stamppot met rauwe andijvie", "Meal", 420, "1 bord", "stamppot andijvie", ["stamppot"]),
  row("zuivelspread", "Zuivelspread (kuip)", "Snack", 250, "100 g", "zuivelspread", ["broodbeleg"]),
  row("vlaflip", "Vlaflip vanille-chocola", "Drink", 110, "150 ml", "vlaflip", ["vla"]),
  row("toffee-vla", "Karamelvla", "Drink", 100, "125 ml", "karamel vla", ["vla"]),
  row("rijstepap", "Rijstepap (kant-en-klaar)", "Drink", 95, "200 g beker", "rijstepap", ["rijst", "ontbijt"]),
  row("griesmeelpap", "Griesmeelpap", "Drink", 90, "200 g", "griesmeel pap", ["ontbijt"]),
  row("karnemelk-linzen", "Linzen in tomatensaus (blik)", "Meal", 110, "250 g", "linzen tomatensaus", ["vegan"]),
  row("bakkerskaasbroodje", "Kaas-uienbroodje", "Snack", 320, "1 stuk", "kaas ui broodje", ["bakker"]),
  row("saucijzenbroodje", "Saucijzenbroodje", "Snack", 340, "1 stuk", "saucijzenbroodje", ["vlees"]),
  row("kaassouffle", "Kaassoufflé", "Snack", 280, "1 stuk", "kaassouffle", ["frituur"]),
  row("loempia", "Loempia klein", "Snack", 200, "1 stuk", "loempia", ["aziatisch"]),
  row("nasi-bami-bami", "Bami goreng (kant-en-klaar)", "Meal", 480, "300 g", "bami goreng", ["noedels"]),
  row("macaroni-kaas-oven", "Macaroni kaas uit de oven", "Meal", 420, "300 g portie", "macaroni kaas", ["pasta"]),
  row("spaghetti-pesto", "Spaghetti met pesto", "Meal", 550, "1 bord", "spaghetti pesto", ["pasta"]),
  row("rijst-kip-curry", "Kipfilet in zoete curry met rijst", "Meal", 520, "450 g", "kip curry rijst", ["afhaal"]),
  row("shoarma-broodje", "Shoarmabroodje met saus", "Meal", 650, "1 broodje", "shoarma broodje", ["afhaal"]),
  row("kipburger-mc-style", "Kipburger (fastfood-achtig)", "Meal", 480, "1 burger", "kipburger", ["fastfood"]),
  row("hamburger-rund", "Hamburger rund", "Meal", 520, "1 burger", "hamburger", ["fastfood"]),
  row("patat-mayo", "Patat met mayonaise (klein)", "Meal", 550, "klein bakje + 2 el mayo", "patat mayo", ["friet"]),
  row("kibbeling", "Kibbeling (gebakken vis)", "Meal", 380, "200 g", "kibbeling", ["vis", "viskraam"]),
  row("haring-ui", "Haring met uitjes", "Meal", 220, "1 portie", "haring ui", ["vis"]),
  row("krentenbol", "Krentenbol", "Snack", 240, "1 stuk", "krentenbol", ["bakker"]),
  row("rozijnenbrood", "Rozijnenbrood (snee)", "Snack", 100, "1 snee", "rozijnenbrood", ["brood"]),
  row("suikerwafel", "Suikerwafel (rond)", "Snack", 180, "1 stuk", "suikerwafel", ["koek"]),
  row("eierkoek", "Eierkoek", "Snack", 150, "1 stuk", "eierkoek", ["koek"]),
  row("gevulde-koek", "Gevulde koek", "Snack", 280, "1 stuk", "gevulde koek amandel", ["koek"]),
  row("tompouce", "Tompouce punt", "Snack", 220, "1 punt", "tompouce", ["gebak"]),
  row("bossche-bollen", "Soes met chocolade (Bossche bol-achtig)", "Snack", 380, "1 stuk", "chocolade soes", ["gebak"]),
  row("oliehoorn", "Oliehoorn / saucijzenbroodje bladerdeeg", "Snack", 360, "1 stuk", "saucijzenbroodje bladerdeeg", ["vlees"]),
  row("bier-pils", "Pilsbier", "Drink", 40, "100 ml", "pils bier", ["alcohol"]),
  row("wijn-wit", "Witte wijn", "Drink", 82, "100 ml", "witte wijn glas", ["alcohol"]),
  row("rose", "Rosé wijn", "Drink", 75, "100 ml", "rose wijn", ["alcohol"]),
];

fs.writeFileSync(out, JSON.stringify(items, null, 2), "utf8");
console.log("Wrote", items.length, "items to", path.relative(root, out));
